# Generated by Django 2.2.4 on 2022-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurrencia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='respuesta_read',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
    ]
