# Generated by Django 2.2.4 on 2022-02-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurrencia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('0', 'Sin cambios detectados'), ('1', 'Se detectaron cambios')], default='0', max_length=1),
        ),
    ]
